# Theme setting
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jemoji
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap

# Site settings
title: The homepage of chanchan
description: encyclopedia of culture
url: "https://chanchanorders.github.io"
baseurl: "/world"

# Build settings
markdown: kramdown

# Image settings
img_path: /assets/images/

# Exclude files from processing (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/